### ISSUE TITLE
Request for Dune addition

### ISSUE THREAD

**Issue by jasonbrandt42** [pbartkowiak-dev/discord-dice-ui#20]
Is there a quick way we could use one of the other 2d20 sections to quickly make a Dune section?   I can provide dice images and other help if needed.

**Comment by pbartkowiak-dev** [comment]
Hi @jasonbrandt42, thanks for reaching out.

I can do this, coupling it with a 2d20 refactor that I planned anyway.

Can you send me assents and give a rundown of changes that have to be implemented in Dune version of 2d20?

**Comment by jasonbrandt42** [comment]
You bet!  I am running the test game this weekend, so I will know everything needed by then.   

Thanks!  :D

**Comment by jasonbrandt42** [comment]
Here is a link to the doc which has the changes.   I listed them as what was different from Conan vs Dune

https://docs.google.com/document/d/1i1kXZr46a0JqnSIqrn-wKFSC5RgafRKV/edit?usp=sharing&ouid=113318684218743138349&rtpof=true&sd=true

**Comment by jasonbrandt42** [comment]
I will have images done later this weekend :)

**Comment by jasonbrandt42** [comment]
added dune images here
https://github.com/jasonbrandt42/discord-dice-ui/tree/dune-addition

**Comment by pbartkowiak-dev** [comment]
Thanks. I've already started to work on it on the branch in my repo https://github.com/pbartkowiak-dev/discord-dice-ui/tree/2d20-refactor

As I mentioned before, I want to refactor 2d20 components first, then I'll add the Dune module. Please be patient ;)

**Comment by jasonbrandt42** [comment]
Awesome!   No rush at all.   Feel free to let me know if you need any more images or icons.  :D

**Comment by pbartkowiak-dev** [comment]
Sorry for the delay, I'm getting back to this soon. Cheers

**Comment by pbartkowiak-dev** [comment]
Hi @jasonbrandt42 

It seems **d6** and **hit dice** are missing for Dune.

![image](https://user-images.githubusercontent.com/18140472/163687922-ef9b439d-f7f8-4010-b567-cce7a0c56a91.png)

Could you upload them as well?

**Comment by pbartkowiak-dev** [comment]
Hi @jasonbrandt42 

I've just finished the Dune mode.

However, no "Scene Tracker" yet. I'll be working on it soon.
