### ISSUE TITLE
TOR: Favored skill test roll wrongly considers Eye of Sauron symbol as a higher roll

### ISSUE THREAD

**Issue by eorea** [pbartkowiak-dev/discord-dice-ui#25]
Whenever a Favored skill test roll is done and the result includes the Eye of Sauron icon in one die vs a roll of a number (1 -10) in the other die, the Eye of Sauron icon is considered as the higher value (11) which leads to the edge case whenever an otherwise successful result is considered as a Failure.

Consider the following screenshot, of a Favoured skill test roll where the result should have been a Success (15 [ 9, 1, 5 ]) instead of Failure (6 [ 0, 1, 5 ]) vs TN 14, since the higher Feat Dice roll was 9 not the Eye of Sauron (0) making it the best result.

![image](https://user-images.githubusercontent.com/19847819/161814949-2126b2db-3008-4b53-8151-e4a757da8d8f.png)

Here is another example, the roll should have been considered a Sucess (22 [ 10, 6, 6 ]) instead of a Failure (12 [ 0, 6, 6 ]) vs TN 14.

![image](https://user-images.githubusercontent.com/19847819/161819270-be929dbe-0ffb-4c96-aae8-83b050fb7d22.png)

This is also happening when the **Rolling for an Adversary** flag is set, as the following screenshot shows, the Favoured adversary skill test should have been a Success (18 [ 9, 4, 5 ]) instead of Failure (9 [ 0, 4, 5 ]) vs TN 14.

![image](https://user-images.githubusercontent.com/19847819/161823837-fc3b47f9-c692-4323-a681-ec77975309b1.png)

As background for this issue I dare to include the following references to TOR 2e Core Rules book:

In p.16 in the **USING YOUR OWN DICE** suggestion block states that if a regular d12 dice is going to be used one should "... remember that on the 12-sided Feat Dice, the 11 is the Eye of Sauron icon and the 12 is a Gandalf rune.", but this is not in any way defining their values as 11 and 12 respectively is talking about the position of the icons physically on the dice.
Further, in p.17 in the **how to read the feat dice** section it specifies that the Gandalf "rune is the greatest result you can get on a Feat Die" and the action success regardless of the total result. The Eye of Sauron "icon is considered to be the worst result possible on a Feat Die" and the result counts as a zero.
Later, in p.20 in the **die roll modifiers** section is stated that Favoured rolls are made rolling "... two Feat dice instead of one, keeping the best result among the two." along Ill-favoured rolls are made rolling "... two Feat dice instead of one, keeping the worst result among the two."
Last but not least, in p.144 in the **FEAT DIE RESULTS FOR ADVERSARIES** suggestion block is stated that whenever "... the Loremaster is making a die roll to resolve an action attempted by a servant of the Shadow, it can be considered more appropriate to the theme to switch the meaning on the two special icons on the Feat Die".

**Comment by pbartkowiak-dev** [comment]
Thank you very much for reporting this issue. I'm on it.
