### ISSUE TITLE
Infinity RPG Addon

### ISSUE THREAD

**Issue by jasonbrandt42** [pbartkowiak-dev/discord-dice-ui#3]
I have created a branch to add Infinity 2d20 to this project.  

Are you able/willing to allow me to submit it as a PR for addition to this project?

**Comment by pbartkowiak-dev** [comment]
Great job, man! Thank you for your contribution. I'm impressed you managed to wade through my crappy code 😅 I reviewed your changes and I have certain suggestions that I'd like you to consider applying.

And one more question, do you plan any further contribution?

**Comment by jasonbrandt42** [comment]
Your code made sense!  I was at least 30% through additions before I realized this was not Angular project :P  

I have made updates to make sure the project works since I first sent a message to ya.    And I have responded to your comments, they were very helpful, thanks! 

I know Angular very well, and React not at all, so some of the changes you need might be a little beyond me at this point :( 

I have updated the code and added most all Infinity tokens.  

If you need any more changes from me, let me know which ones and I can check to see if I know how to make them.  Otherwise I am not sure how much more use I can be.  

I can, however, easily update any icons or images as needed.  

Cheers!

**Comment by jasonbrandt42** [comment]
Also note that I have been able to serve this locally on my machine and use my Discord integration link to verify the Infinity section works as expected.  Though I have not exhaustively tested it yet.  So there may be areas which still need tweaks.

**Comment by jasonbrandt42** [comment]
Any chance we could add what I have now so I can try and use it? 

Thanks!

**Comment by pbartkowiak-dev** [comment]
I accepted your pull request and used the opportunity to fix some minor issues. The new version is on! Thanks again for your work :)

**Comment by jasonbrandt42** [comment]
Thank you so much!   You rock!
