### ISSUE TITLE
L5R - Dice Roller

### ISSUE THREAD

**Issue by jasonbrandt42** [pbartkowiak-dev/discord-dice-ui#37]
L5R 5e allows for explosion re-roll of both d6 and d12 type dice.  

Currently it only allows for adding d6 type dice 

Request: add same functionality for adding d12 dice.

**Comment by jasonbrandt42** [comment]
I am happy to make this change if you are ok with that @pbartkowiak-dev  :D

**Comment by pbartkowiak-dev** [comment]
> I am happy to make this change if you are ok with that @pbartkowiak-dev :D

Sure. Create a new PR and we'll see ;)

**Comment by pbartkowiak-dev** [comment]
...and it's done.

As always, thank you for reporting :)

**Comment by jasonbrandt42** [comment]
You are amazing!   Thank you so much!!!

**Comment by jasonbrandt42** [comment]
@pbartkowiak-dev     Is there a deploy to publish the changes that still needs to be done? 

I don't see the Skill die added to the + add die dropdown (but I see it in the code) 

https://i.ibb.co/mBzXzTR/Untitled-1.jpg

**Comment by pbartkowiak-dev** [comment]
Deploy is automatic.

I haven't fix this dropdown, I've fixed this one:

![image](https://user-images.githubusercontent.com/18140472/197357130-e37ee023-ca31-4c64-82de-116100d517e2.png)

So it's still to be done 👍 

However, can you tell me which feature let you add a new Skill Dice to the roll in the first dropdown? I must have missed it in the book.

**Comment by jasonbrandt42** [comment]
Page 21 , Core Rules

ExPlosive Success ()
The explosive success symbol () represents a particularly effective part of the character’s effort. In addition to
counting as a  symbol, it gives the character a chance
to **roll an additional die** and decide whether to add its
result to the check—potentially letting them succeed at
a task they normally couldn’t overcome.  See  under
Step 6: Resolve Symbols of Kept Dice, on page 24.

And then Page 24 
STeP 6: Resolve Symbols
on KePT Dice

: For each (explosion) symbol, the player rolls one
additional die of the same type as the one containing the  symbol. After rolling a die this way,
the player chooses whether it will be kept (on
top of their current results) or dropped. If the die
is kept, the player resolves its result in addition
to the results on the rest of the kept dice in the
dice pool (including further  symbols).

**Comment by jasonbrandt42** [comment]
So this means that if you get [explosion] symbol on d12, then you roll additional d12.

**Comment by pbartkowiak-dev** [comment]
Rolling additional die to the Explosive Success is available in the next step:
![image](https://user-images.githubusercontent.com/18140472/197359155-3b9138cc-f91e-4a62-9215-53a4702e3c6b.png)

**Comment by jasonbrandt42** [comment]
Ok!  I see that now.  I did not realize I could click after the final kept step. 

It works perfect, thanks!

**Comment by pbartkowiak-dev** [comment]
No problem!

I tried to follow the steps described in the book exactly, even though it wasn't obvious at times.

**Comment by jasonbrandt42** [comment]
It's great!   we are using it for game right now as we speak.  Thanks so much! :D
