### ISSUE TITLE
Dune 2d20 dice roller : Focus is capped to 5 instead of 8

### ISSUE THREAD

**Issue by JMLeMage** [pbartkowiak-dev/discord-dice-ui#41]
Hello, me and my players appreciate your Dice UI very much ! So I must submit this little bug to improve it even more ;)

In the Dune 2d20 system, there is a difference from the other 2d20 systems in the way Focus works:
Focus threshold is fixed by the Skill rank, and in Dune Skill ranks goes from 4 to 8.

Request:
Change the Skill Test window so that **the 'Foc' field is not capped to 5**, but to **8**.
(The tip on the question mark is still accurate)

**Comment by pbartkowiak-dev** [comment]
Thanks for the heads-up!
