### ISSUE TITLE
Less steps in the L5R 5e dice reports in Discord chat

### ISSUE THREAD

**Issue by JMLeMage** [pbartkowiak-dev/discord-dice-ui#46]
Currently, for L5R dice, a report in sent to the discord chat at each step of decision of the roll :
1. Initial roll result
2. Kept dice
3. Modified dice
4. Dice explosion (if kept)

That is useful for meaningful tests, in which players are cooperating to decide the best issue with the player making the test. And it is also a good way to help new players to learn how to make their first tests.

But during intense dice rolling phase like combat, with multiple players rolling in parallel, the numbers of reports sent is rather confusing and not helpful.

Proposed resolution:
Add a checkbox in the L5R 5e dice roll interface, to make/remove all the intermediate reports. In the "less verbose" mode, only the final result is sent and displayed in the Discord chat.
To achieve that, of course, there is a need to also add to the current interface a final "Done" button for the player to indicate that the process is fully done (dice explosions and selection included).

**Comment by pbartkowiak-dev** [comment]
I like the idea. Give me a couple of days 👷
