### ISSUE TITLE
Conan 2d20 and Infinity 2d20 are broken?

### ISSUE THREAD

**Issue by LoZeno** [pbartkowiak-dev/discord-dice-ui#5]
The Skill test does not count successes anymore, nor takes into account focus, target number or anything about 2d20 really...

All they do is give the SUM of the rolls, the highest and the lowest - but they are of no importance for a 2d20 skill roll.

**Comment by pbartkowiak-dev** [comment]
Thanks for the heads up. I'm working on a major refactor. It should be fine now.
