### ISSUE TITLE
Heroku App down

### ISSUE THREAD

**Issue by jasonbrandt42** [pbartkowiak-dev/discord-dice-ui#55]
Not sure where best to note this, but the heroku instance of this dice roller has gone down

 @pbartkowiak-dev

**Comment by pbartkowiak-dev** [comment]
Thanks for letting me know. I hope it's temporary. Otherwise, I'll look at it later.

**Comment by pbartkowiak-dev** [comment]
I've restated the app and it seems to work. Thanks again!

**Comment by jasonbrandt42** [comment]
You are awesome, thanks so much!!!
